### PR TITLE
Switch domain name

### PR DESCRIPTION
**Pull request by btcdrak**
This will be merged on January 15th after 15:00UTC

### CODE REVIEW

**Comment by luke-jr** [comment]
We can't use both?

**Comment by btcdrak** [comment]
@luke-jr bitcoinco.re will be redirected to bitcoincore.org for the time being, certainly cant have duplicated content but still could use the bitcoinco.re domain for other things. People just prefer the .org

**Comment by harding** [comment]
If I recall correctly, there was other stuff previously hosted on BitcoinCore.org, such as downloads for the Gitian compile and some fee analysis stuff by Gavin.  What has happened to that?

**Comment by btcdrak** [comment]
@harding moved to a subdomain. The gitian stuff is only a backup URL.

**Comment by harding** [comment]
@btcdrak cool.  Then, ACK.

**Pull request merged**
