### PR TITLE
Proposed statement condemning censorship

### PR DESCRIPTION
**Pull request by btcdrak**
This is my own proposal.

If you agree to this being posted, please ""ACK 92228f2". If you would like to add your signature, please add your name + ACK in a comment i.e. "ACK 92228f2 (your name)"

### CODE REVIEW

**Comment by CodeShark** [comment]
ACK

**Comment by dexX7** [comment]
ACK

**Comment by btcdrak** [comment]
Remember you need to add your names to the ACK if you want to add your name to the letter. Let's make it 

"ACK statement 92228f2 (your name)"

**Comment by jonasschnelli** [comment]
ACK 92228f2488f8c9f3da8d284326ac12b1ec4d4f1e statement.

**Comment by jl2012** [comment]
ACK 92228f2 (Johnson Lau, jl2012)

**Comment by carnesen** [comment]
ACK statement 92228f2
<https://github.com/bitcoin-core/website/commit/92228f2488f8c9f3da8d284326ac12b1ec4d4f1e>
(Chris
Arnesen)

**Comment by instagibbs** [comment]
Being more specific on the behavior I think people I object to(as well as myself personally), as "censorship" is a misnomer to me in this case:

"Individuals in the Bitcoin community have the right in the proper venue to discuss civilly any and all changes to the system, and to critique these changes without silencing others."

**Comment by btcdrak** [comment]
Closing for alternative

**Pull request closed without merging**
