### PR TITLE
Overhaul navigation bar

### PR DESCRIPTION
**Pull request by jonasschnelli**
- new logo
- align navigation and logo

Should look like:
bildschirmfoto 2016-01-11 um 15 16 51

### CODE REVIEW

**Comment by jonasschnelli** [comment]
[WIP] need to align the logo better...

**Comment by jonasschnelli** [comment]
Now the logo should stay in vertical align with the navigation (when resizing).

**Comment by btcdrak** [comment]
I'm not sure about the logo. Letter kerning seems too close and jet black seems a bit harsh.

**Comment by jonasschnelli** [comment]
Changes to gray logo, used >30 kerning.
bildschirmfoto 2016-01-11 um 16 04 12

The idea is to get it in align with the dmg background (which might be once extended to the splash/about screen of core):
bildschirmfoto 2016-01-11 um 16 04 57

**Comment by jonasschnelli** [comment]
closing for now...

**Comment by btcdrak** [comment]
I agree we should unify the logo with what we put in the software, but we need to cater for non-retina users too :)

**Pull request closed without merging**
