### PR TITLE
Update video embed

### PR DESCRIPTION
**Pull request by btcdrak**
This video was re-rendered by @jonasschnelli

### CODE REVIEW

**Comment by MarcoFalke** [comment]
utACK

**Comment by harding** [comment]
Tested ACK

**Comment by jonasschnelli** [comment]
Give me another day. I'd like to add a informative slide after the into-slide (total PRs, total commits, total authors). I also try to upload it to youtube to compare the quality.

**Comment by jonasschnelli** [comment]
@btcdrak: can you use this one: https://www.youtube.com/watch?v=FIt7GLxxIpY&feature=youtu.be&vq=hd1080?

**Comment by jonasschnelli** [comment]
"Full quality" video: https://bitcoin.jonasschnelli.ch/core_2015_fullhd.mov

**Pull request merged**
