### PR TITLE
Use black navigation bar, use different logo

### PR DESCRIPTION
**Pull request by jonasschnelli**
Would look like:
bildschirmfoto 2016-01-14 um 10 20 57

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Awesome! ACK, looks more legit now.

**Comment by carnesen** [comment]
Looks great!

**Comment by harding** [comment]
Tested ACK.  I agree that it looks a lot nicer now.  Thanks!

**Comment by jonasschnelli** [comment]
Rebased.
Adapted the nested menus for the black style.
Slightly reduce the required size for the logo. The logo now auto-resizes and does not overflows into the navigation anymore.

**Comment by MarcoFalke** [comment]
Concept Re-ACK a6853a4

**Comment by jonasschnelli** [comment]
Testsite: https://coresitetest.jonasschnelli.ch

**Comment by MarcoFalke** [comment]
Tested ACK a6853a4 ;)

**Comment by MarcoFalke** [comment]
Can you make the white highlights have round edges?

screenshot from 2016-01-14 19-49-59

**Comment by jonasschnelli** [comment]
Added a commit: add round corners to the active navigation item state.

bildschirmfoto 2016-01-14 um 21 22 32
bildschirmfoto 2016-01-14 um 21 22 13

**Comment by btcdrak** [comment]
Looks good, let's merge it... I've a couple of niggles but they can be worked out later.

**Comment by MarcoFalke** [comment]
ACK. Let's merge the eye candy.

**Pull request merged**
