### PR TITLE
In-sentence line-break removal for Transifex compatibility 

### PR DESCRIPTION
**Pull request by mably**
To facilitate translating with Transifex, every sentence should be kept on one line only.

This PR removes two extra line-breaks present in two french version pages.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by btcdrak** [comment]
This doesnt matter now, because we're taking the content from the English and this file will be overwritten when Transifex is translated.

**Comment by MarcoFalke** [comment]
Sure, it would need adjustment in the English source, I guess?

**Comment by btcdrak** [comment]
@MarcoFalke Yes. So long as `en` has no line breaks mid sentence then all is good for Transifex.

**Comment by mably** [comment]
@btcdrak you asked me to make this PR this afternoon on slack, did I missed something?

**Comment by btcdrak** [comment]
@mably We only need to worry about the English. The rest comes from Transifex.

**Comment by mably** [comment]
Ok I missed that part I guess, do you want me to redo it for the corresponding english pages?

**Comment by btcdrak** [comment]
I think I fixed it earlier. Please check.

**Comment by mably** [comment]
@btcdrak nope, these two line-breaks are still present in the original english files.

**Comment by btcdrak** [comment]
Then PR the English.

**Comment by mably** [comment]
Ok

**Pull request closed without merging**
