### PR TITLE
Overhaul footer, add links, change copyright

### PR DESCRIPTION
**Pull request by jonasschnelli**
* Redesign footer.
* Add link to github
* Change copyright from "Bitcoin Core" to "Bitcoin Core Developers" (matches source code copyrights then)

bildschirmfoto 2016-01-15 um 14 10 55

Testsite: https://coresitetest.jonasschnelli.ch/en/about/

### CODE REVIEW

**Comment by harding** [comment]
LGTM

**Comment by MarcoFalke** [comment]
ACK, looks great!

**Comment by btcdrak** [comment]
Merged in 9acf151

**Comment by MarcoFalke** [comment]
This is missing the following. Was this on purpose?

```diff
diff --git a/_config.yml b/_config.yml
index 0bc0fa4..e31dcc4 100644
--- a/_config.yml
+++ b/_config.yml
@@ -25,7 +25,7 @@ kramdown:
 
 # Site owner
 owner:
-  name: Bitcoin Core
+  name: Bitcoin Core Developers
   avatar: bio-photo.jpg
   bio: ""
   email:

**Comment by btcdrak** [comment]
@MarcoFalke Yes. This PR is a design only PR and there were discussions about this before, rather than hold up this PR I chose to remove it (after discussing with @jonasschnelli).

**Pull request closed without merging**
