### PR TITLE
Add segwit adoption page

### PR DESCRIPTION
**Pull request by btcdrak**
Todos:

- [x] Add into menu structure
- [x] Front Matter

screenshot-localhost 4000 2016-01-14 23-57-15

### CODE REVIEW

**Comment by dcousens** [comment]
ACK for bitcoinjs-lib

**Comment by dcousens** [comment]
ACK for [EI8HT Wallet](http://ei8.ht/)

**Comment by dexX7** [comment]
Not sure, if it qualifies, but ACK for [Omni Core](https://github.com/OmniLayer/omnicore) (Bitcoin Core fork with Mastercoin/Omni extensions). Status: planned, not ready.

**Comment by rubensayshi** [comment]
if any bitcore-lib people show up to this ticket; 

we've started working on bitcoinjs-lib already, if time allows it (and it should) I also want to port that to bitcore-lib 

so poke me plz ;-) (rubensayshi on IRC, bitcoinjs slack or ruben@blocktrail)

**Comment by bpdavenport** [comment]
ACK for BitGo

**Comment by adam3us** [comment]
ACK (for self)

**Comment by nvk** [comment]
ACK Coinkite

**Comment by CodeShark** [comment]
ACK

**Comment by jonasschnelli** [comment]
ACK (digitalbitbox, libbtc). ACK general page concept.

**Comment by harding** [comment]
For myself, ACK general page concept.  @btcdrak What is the "#" column for?

**Comment by btcdrak** [comment]
@harding It's a visual to easily count the number of supporting services.

**Comment by btcdrak** [comment]
I'm going to go ahead and merge this now, sooner we have it up the better.

**Comment by ecdsa** [comment]
ACK for Electrum

**Comment by prusnak** [comment]
ACK for TREZOR

**Comment by samouraiwallet** [comment]
We're already listed but to make it official ...

ACK for Samourai Wallet

**Comment by mycelium-com** [comment]
ACK for Mycelium Wallet

**Comment by richardkiss** [comment]
ACK for [pycoin](https://github.com/richardkiss/pycoin)

**Comment by obi** [comment]
ACK for Coinfloor Exchange

**Comment by petertodd** [comment]
ACK python-bitcoinlib, planned, not ready

**Comment by schildbach** [comment]
I have put up a [rough roadmap](https://groups.google.com/forum/#!topic/bitcoinj/Dz7nI9oCZAw) for segwit in [bitcoinj](https://github.com/bitcoinj/bitcoinj).

**Comment by gary-rowe** [comment]
ACK for [MultiBit HD](https://multibit.org).

**Comment by afk11** [comment]
ACK for [https://github.com/Bit-Wasp/bitcoin-php|bitcoin-php]

**Comment by mklords** [comment]
ACK for Airbitz. planned but not ready. will be ready soon.

**Comment by luke-jr** [comment]
ACK libblkmaker (planned & ready as much as can be at this point), Eloipool (planned only), and Bitcoin LJR.

Can we also list Bitcoin Core here?

**Comment by btcdrak** [comment]
> Can we also list Bitcoin Core here?

sure, just seemed obvious :) will all

**Comment by bithernet** [comment]
ACK for [Bither Wallet](https://bither.net).

**Comment by dcousens** [comment]
@btcdrak I noticed you added a "depends" column.
[EI8HT](http://ei8.ht/) depends on [bitcoin core](https://bitcoincore.org/) and [bitcoinjs](https://github.com/bitcoinjs/bitcoinjs-lib)

**Comment by dexX7** [comment]
Omni Core depends on Bitcoin Core.

**Comment by luke-jr** [comment]
Eloipool is ready (with segnet working): https://github.com/luke-jr/eloipool/tree/segwit

**Comment by wizkid057** [comment]
ACK for [Eligius](http://eligius.st) (planned).

**Comment by luke-jr** [comment]
Sorry, please change Eloipool's "ready" to "partial". It only works for stratum/getwork, not as a GBT *server*, at the moment.

**Comment by shesek** [comment]
ACK for [Bitrated](https://www.bitrated.com/) (planned).

**Comment by jspri3** [comment]
ACK
www.smartbit.com.au (planned: yes, ready: yes)

**Comment by afk11** [comment]
Can you update the bitwasp library? We have full signing and verification support.

**Comment by btchip** [comment]
can you update Ledger ? We are WIP - fully done, pending more integration and finalized testing in a few days (with Greenbits then our own wallet)

**Comment by chjj** [comment]
ACK for [bcoin](https://github.com/indutny/bcoin) - full block validation and wallet/signing support

**Comment by pollastri-pierre** [comment]
Hi, can you update Ledger Wallet Chrome app. We actually don't depend on bitcoinjs to support segwit ?

**Comment by braydonf** [comment]
ACK (initial wip support at https://github.com/braydonf/bitcore-lib/tree/segwit @rubensayshi)

**Comment by miguelmorales85** [comment]
ACK for [Copay](https://github.com/bitpay/copay/issues/3844#issuecomment-200359654)

**Comment by jaminunit** [comment]
ACK for [Vaultoro](https://www.vaultoro.com)

**Comment by droark** [comment]
ACK for [Armory](https://github.com/goatpig/BitcoinArmory/tree/SegWit) (depends on Core). It's not ready yet but work is progressing, with every intention that Armory will be ready well before SegWit is activated.

**Comment by sstone** [comment]
ACK for [bitcoin-lib](https://github.com/ACINQ/bitcoin-lib) (planned: yes, status: wip, notes: library)

**Comment by mdeneuville** [comment]
ACK for Kaiko (planned: yes, status: no, notes: explorer )

**Comment by slush0** [comment]
Please update Trezor; ready: yes

**Comment by BitLox** [comment]
BitLox hardware wallet SegWit support is in the planning stage.

**Pull request merged**
