### PR TITLE
[About] Mention source of website

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Meta question: Should this mark the translations dirty?

**Comment by btcdrak** [comment]
I prefer to keep this in the "contributing" section. The version number should be updated according to https://github.com/bitcoin-core/website/blob/gh-pages/CONTRIBUTING.md#translations

**Comment by btcdrak** [comment]
Maybe contributing can be improved here: 
screen

**Comment by MarcoFalke** [comment]
Ok, I will have a closer look next week.

**Pull request closed without merging**
