### PR TITLE
[blog] Add commit visualisation for 2015

### PR DESCRIPTION
**Pull request by btcdrak**
cacrqdp

### CODE REVIEW

**Comment by CodeShark** [comment]
ACK

**Comment by jmcorgan** [comment]
Don't have the time atm to render locally, so utACK. Might want to explain just a bit more the benefits of the new features, but it is good as-is.

**Comment by jonasschnelli** [comment]
Hmm.. not sure, tend to NACK. First, I don't see a big value in adding the visualization. Second: the music is just so cheesy.

**Comment by MarcoFalke** [comment]
Oh, and the music may be copyrighted. I don't understand copyright well enough to understand what this means for us but I'd rather not risk getting a DMCA takedown.

**Comment by btcdrak** [comment]
@MarcoFalke It's embedded content from Youtube.

**Comment by MarcoFalke** [comment]
@jonasschnelli Would you ACK if the video was removed (or muted)?

**Comment by jonasschnelli** [comment]
I think plain stats (amount of commits per month, per year), probably not user based (we don't want to raise a competition here) would be better. If website visitors could quick get the current activity rate (in commits-per month / comments per day / etc.) that would be nice IMO.

The visualization is just a gimmick IMO that has not much of a value.

**Comment by adam3us** [comment]
ACK. maybe some stats later but publish ACK

**Comment by btcdrak** [comment]
We can add more details after but I think we should go ahead and publish this now.

**Comment by harding** [comment]
Can we leave more time for review next time?  I just finished watching, and the video has CLTV mixed up with Strict DER:

[Caption below says "July 2015" and "CLTV activation"]

screenshot 2016-01-13 at 09 19 03 - display 1

**Comment by btcdrak** [comment]
@harding I contacted the author about this earlier this morning. He will update the annotations. @jonasschnelli is also going to make a version with avatars plus some extra charts.

**Comment by PRabahy** [comment]
Oops, hadn't been on reddit in a few days. I'll fix the CLTV Activation annotation.

The music was something that was recommended and inserted by youtube itself, so I assume that youtube already figured out any copyright issues. If anyone is interested in doing more research it is Blue Collar by Gavin Froome.

Looks like the idea was redone at https://www.youtube.com/watch?v=FIt7GLxxIpY and I think I like the way those annotations were done a bit more.

**Pull request merged**
