### PR TITLE
Switch website to live mode

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
ACK

**Comment by jl2012** [comment]
ACK

**Comment by harding** [comment]
ACK.

**Comment by jmcorgan** [comment]
ACK

**Comment by instagibbs** [comment]
ACK

**Comment by CodeShark** [comment]
ACK

**Comment by laanwj** [comment]
ACK

**Comment by jonasschnelli** [comment]
ACK

**Comment by sipa** [comment]
ACK

**Comment by greenaddress** [comment]
ACK

**Pull request merged**
