### PR TITLE
Italian translation of contribute.md

### PR DESCRIPTION
**Pull request by gabridome**

### CODE REVIEW

**Comment by btcdrak** [comment]
needs rebase

**Comment by btcdrak** [comment]
bump

**Comment by btcdrak** [comment]
I have opened a Transifex for Italian https://www.transifex.com/bitcoincore/bitcoincoreorg/language/it/

**Comment by gabridome** [comment]
thank you.

On Tue, Jan 26, 2016 at 12:12 PM, ฿tcDrak <notifications@github.com> wrote:

> I have opened a Transifex for Italian
> https://www.transifex.com/bitcoincore/bitcoincoreorg/language/it/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin-core/website/pull/26#issuecomment-174959957>.
>



-- 
Please avoid unnecessary attachments. Write in the body of the message.
Thank you.

Gabriele Domenichini
pgp fingerprint: DC47 A9B4 CF41 6373 6EBB  E14E A48F BF05 1C43 F817
Ƀ: https://greenaddress.it/it/pay/GA2zwPHGcVxy1MA79PKYPxrk672FrE/

**Pull request closed without merging**
