### PR TITLE
Add RBF FAQ

### PR DESCRIPTION
**Pull request by btcdrak**
- [ ] Needs polishing
- [ ] add to navigation

### CODE REVIEW

**Comment by dcousens** [comment]
Looks good @btcdrak :+1:

**Comment by dcousens** [comment]
@greenaddress did you have any novel use case that isn't listed here?

**Comment by greenaddress** [comment]
@dcousens not really, we plan to support the main wallet use cases such as bump fee to begin with and then more advanced features to update unconfirmed transaction with new input and output when sending transactions in quick succession, etc

**Comment by btcdrak** [comment]
Not sure now this got merged, I must have mad a mistake on the command line.

**Comment by btcdrak** [comment]
Reopened in #60

**Pull request merged**
